version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    env_file: .env 
    volumes:
      - ${VOLUME_PATH}:/var/lib/mysql
    restart: on-failure
    networks:
      - my-network

  library-bot:
    build: 
      context: ./
      dockerfile: Dockerfile  
    container_name: library-bot
    ports:
      - "4000:4000"
    networks:
      - my-network
    restart: on-failure 
    depends_on:
      - mysql

networks:
  my-network:
    driver: bridge
