exports.MENU_OPTIONS = 'Menu:\n1. Display all available books\n2. My Books'
exports.WELCOME_MESSAGE = "Welcome to the Book Library"
exports.QUERY = 'SELECT * FROM library.books WHERE quantity_available > 0';
exports.ERROR_FETCHING_BOOKS = "Error fetching available books. Please try again later.";
exports.ERROR_FETCHING_USER = "Error fetching user. Please try again later.";
exports.NO_BOOKS_FOUND = 'No available books found.';
exports.AVAILABEL_BOOKS = "Available Books:";
exports.USE_START_COMMAND_MESSAGE = 'Please start with `/start` before using other commands.';
exports.ERROR_DURING_USER_CHECK = "An error occurred during user check. Please try again later.";
exports.HELP_MESSAGE = "Please enter !help to get available commands."
exports.CHECKED_BOOK_SUCCUESSFULLY_MESSAGE = "Book successfully checked out:"
exports.ERROR_CHECKED_OUT_MESSAGE = 'Error during checkout. Please try again.'
exports.GET_AVAILABLE_BEFORE_CHECKOUT_MESSAGE = 'Please use `/1` command to get the list of available books before using /checkout.'
exports.ALREADY_CHECKED_OUT_BOOK_MESSAGE = "You already have checked out this book return it to checkout again."
exports.NO_CHECKED_OUT_BOOK_MESSAGE="No checked out books"
exports.MY_BOOKS="My books"