exports.MENU_OPTIONS = 'Menu:\n1. Display all available books'
exports.WELCOME_MESSAGE = "Welcome to the Book Library"
exports.QUERY = 'SELECT * FROM library.books WHERE quantity_available > 0';
exports.ERROR_FETCHING_BOOKS = "Error fetching available books. Please try again later.";
exports.ERROR_FETCHING_USER = "Error fetching user. Please try again later.";
exports.NO_BOOKS_FOUND = 'No available books found.';
exports.AVAILABEL_BOOKS = "Available Books:";
exports.USE_START_COMMAND_MESSAGE = 'Please start with `/start` before using other commands.';
exports.ERROR_DURING_USER_CHECK = "An error occurred during user check. Please try again later.";