name: CI/CD with Docker

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm test

  build:
    runs-on: ubuntu-latest

    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t library-bot .

  deploy:
    runs-on: self-hosted

    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull latest changes from GitHub repository
        run: |
          cd /home/library-bot/library-bot && git pull origin main

      - name: Build Docker image
        run: |
          cd /home/library-bot/library-bot && docker build -t library-bot .

      - name: Stop and remove existing container
        run: |
          docker stop library-bot || true
          docker rm library-bot || true

      - name: Run the new container
        run: docker run -d --name library-bot -p 4000:4000 library-bot

      - name: Check if container is running
        run: |
          if docker ps | grep -q library-bot; then
              echo "Docker container library-bot successfully started."
          else
              echo "Error: Failed to start Docker container library-bot."
              exit 1
          fi

