name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js and npm
      uses: actions/setup-node@v2
      with:
        node-version: '20.11.1'

    - name: Install dependencies and deploy
      run: |
        npm install
        npm install pm2 -g
        chmod +x script.sh
        ./script.sh